language: rust
sudo: required

dist: trusty
rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - TRAVIS_NODE_VERSION="7"

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install ${TRAVIS_NODE_VERSION}
  - nvm use ${TRAVIS_NODE_VERSION}

matrix:
  allow_failures:
    - rust: nightly

script: |
  npm test