language: rust
sudo: required

dist: trusty
rust:
  - stable
  - beta
  - nightly

before_install:
  - source $HOME/.nvm/nvm.sh
  - nvm install 7
  - nvm use 7

matrix:
  allow_failures:
    - rust: nightly

script: |
  npm test